[features]
resolution = true
skip-lint = false

[programs.localnet]
auction = "9QUtGjgmcPE3G5wLyF6QRgocAtG7dZZ7madGaGYmXVeP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[toolchain]
anchor_version = "0.31.1"
solana_version = "3.0.13"

[build]
tools_version = "v1.52"